### ISSUE TITLE
Postfix service definition hides the client IP address

### ISSUE THREAD

**Issue by laszlokulcsar** [technicalguru/docker-mailserver#10]
By default "spec.externalTrafficPolicy" rewrites the source IP address to the EXTERNAL-IP of the service, therefore we can not distinguish between different sources on postfix level.

Reference: [https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip)

PR for possible solution:  [Add TrafficPolicy to postfix service #9 ](https://github.com/technicalguru/docker-mailserver/pull/9/commits/30578b1096700bdd997d42193dc2f978b8211514)

**Comment by technicalguru** [comment]
PR merged
