### ISSUE TITLE
PFA_SETUP_PASS suggests using db root password

### ISSUE THREAD

**Issue by pixil98** [technicalguru/docker-mailserver#3]
The Kubernetes example yaml suggests using the root password for the database as the value for PFA_SETUP_PASS. It would be better to recommend a unique password for postfixadmin. As far as I can tell this isn't used anywhere to connect to the database and is only being used to authenticate the user when logging into the setup page.

**Comment by technicalguru** [comment]
Hello pixil98,

the database itself has a root password usually. This was meant here. You will need this when the database was not setup yet before.

It is not the root password of the host machine.

**Comment by pixil98** [comment]
I'm referring to these lines in examples/kubernetes/deployments/postfixadmin.yaml

```
        - name: PFA_SETUP_PASS
          value: "<my-mariadb-root-password>"
```

I'm pretty sure it isn't using this password to actually connect to the database since it only seems to connect as the postfix user. I believe this should be a unique password for configuring postfixadmin.

**Comment by technicalguru** [comment]
Oh, that's most likely a copy-and-paste leftover, I'll fix it. in the docs. Thanks

**Comment by technicalguru** [comment]
Fixed in develop branch - to be published with next release
