### ISSUE TITLE
Postfix container example is missing DKIM env vars

### ISSUE THREAD

**Issue by pixil98** [technicalguru/docker-mailserver#4]
The postfix container won't talk to opendkim out of the box (following the kubernetes example). It's missing environment variable declarations for PF_DKIM_SERVICE_NAME and PF_DKIM_SERVICE_PORT from the yaml.

**Comment by technicalguru** [comment]
Yes, that is correct. The DKIM container does not work out of the box without further setup. However, the vars are missing and not mentioned there (as opposed to HELM examples). I added them now.
